name: vnpay
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: wao.flutter.application.project.vnpay
        pluginClass: VnpayPlugin
      ios:
        pluginClass: VnpayPlugin
